CREATE SEQUENCE PET_SEQ START WITH 1 INCREMENT BY 1000;

CREATE TABLE PET (
    ID          BIGINT  NOT NULL    DEFAULT NEXTVAL('PET_SEQ'),
    TAGS_JSON   JSONB   NOT NULL,

    CONSTRAINT PET_PK PRIMARY KEY (ID)
);

CREATE INDEX PET_TAG ON PET USING gin ((TAGS_JSON -> 'tags'));
